### ISSUE TITLE
您好，我想问一下您的设备的配置

### ISSUE THREAD

**Issue by 01070** [CRIPAC-DIG/TextING#1]
我在生成AG_NEWS的图的时候感觉似乎内存不太够

**Comment by Magicat128** [comment]
您好，我们实验的机器为120G。可以检查一下哪一步内存不够，目前是将所有图处理完后统一存储，可以考虑训练/验证/测试集分开执行。

**Comment by xhjcxxl** [comment]
我的机器也是120G，但是跑20ng数据集的时候，报内存不够

**Comment by A11en0** [comment]
120G说的是显存？这什么卡？
