### ISSUE TITLE
关于不同数据集的超参数问题

### ISSUE THREAD

**Issue by chenchongyuan** [CRIPAC-DIG/TextING#10]
您好，想请问一下您论文中各个数据集取得的最好分数，都是使用默认的超参数得到的吗？还是不同数据集有各自的一组参数？

**Comment by Magicat128** [comment]
您好 @chenchongyuan 

默认参数是一个相对通用的值，实际使用的参数略有不同，batch_size和hidden_size上可能要大一些。

**Comment by chenchongyuan** [comment]
好的，谢谢您的回复
