### ISSUE TITLE
Model performance on long documents

### ISSUE THREAD

**Issue by pwnywiz** [CRIPAC-DIG/TextING#15]
Hello,
Great work and thanks for sharing the code.
I am interested in doing fake news classification in greek articles and your model seems like a nice idea to try.
What I would like to ask is, if you have tried the model in any other language apart from english and most importantly, if you have tested it in long documents with length of over 500 words.
Thank you very much.

**Comment by Magicat128** [comment]
@pwnywiz 

Hi, 
seems to be a duplicate issue from email. Please check if you received my email reply. Feel free to re-open this issue if you have further questions. Thank you.
