### ISSUE TITLE
关于20ng数据集疑问

### ISSUE THREAD

**Issue by xhjcxxl** [CRIPAC-DIG/TextING#9]
你好，我是用此模型跑20ng数据集的时候，提示内存不足，不知道你们是怎么处理的

**Comment by Magicat128** [comment]
你好 @xhjcxxl ，

可能是因为个别文档长度较大的原因，导致padding后整体开销变大。可以考虑对长文档进行截断之类的操作，见build_graph.py第32-33行。

**Comment by xhjcxxl** [comment]
请问，论文中所有的测试结果都是经过截断操作的吗？（我自己测试的时候，不截断也可以跑起来）

**Comment by xhjcxxl** [comment]
谢谢，20ng通过截断后，能够跑起来了

**Comment by Magicat128** [comment]
论文中的结果都是未截断的。

**Comment by xhjcxxl** [comment]
明白了，谢谢
